#ifndef LV_POCKET_ROUTER_SRC_CONN_GUIDE_MANUAL_CONN_H_
#define LV_POCKET_ROUTER_SRC_CONN_GUIDE_MANUAL_CONN_H_

void manual_conn_create(void);


#endif /* LV_POCKET_ROUTER_SRC_CONN_GUIDE_MANUAL_CONN_H_ */
