#ifndef LV_POCKET_ROUTER_SRC_UTIL_ADMIN_SETTINGS_H_
#define LV_POCKET_ROUTER_SRC_UTIL_ADMIN_SETTINGS_H_

enum ADMIN_LOGIN_IDS {
    ID_ADMIN_COLUMN,
    ID_PASSWORD_COLUMN,
};
void admin_login_create();

#endif /* LV_POCKET_ROUTER_SRC_UTIL_ADMIN_SETTINGS_H_ */
