#ifndef LV_POCKET_ROUTER_SRC_SETTINGS_BATTERY_OPTIMIZE_H_
#define LV_POCKET_ROUTER_SRC_SETTINGS_BATTERY_OPTIMIZE_H_

#ifdef BATTERY_OPTIMIZE_SUPPORT
void battery_optimize_create(void);
#endif

#endif /* LV_POCKET_ROUTER_SRC_SETTINGS_BATTERY_OPTIMIZE_H_ */
